In [1]:
import fileHandle
from scipy.fft import fft, ifft, fftfreq
import matplotlib.pyplot as plt
import numpy as np
import cmath
%matplotlib widget
from mpl_toolkits import mplot3d

In [2]:
filePath = "EMG_data_for_gestures-master/*/*.txt"
# filePath = "EMG_data_for_gestures-master/01/1_raw_data_13-12_22.03.16.txt"
data, fileList = fileHandle.readFiles(filePath)

print(fileList[0])
print(data[0][:,0])
# data[filenumber][:,(0 = time(ms), 1 = channel1, 2 = channel2, ... , 8 = channel8, 9 = class)]

EMG_data_for_gestures-master/08/1_raw_data_12-14_23.03.16.txt
[1.0000e+00 4.0000e+00 5.0000e+00 ... 6.2922e+04 6.2923e+04 6.2924e+04]


In [38]:
fig, ax = plt.subplots(nrows=2, ncols=3)

# channel used array
chi = data[0][:,1]
# class array
cl = data[0][:,9]

mfreq = np.zeros((6))
mamp = np.zeros((6))

count = 1
for row in ax:
  for col in row:
    # specify class
    cli = np.where(cl == count)

    # select channel of class
    chicli = chi[cli]
    # print(chicli)

    # y = np.zeros((len(chicli)))
    y = fft(chicli)
    n = chicli.size
    timestep = 0.001
    freq = np.fft.fftfreq(n, d = timestep)
    # plt.figure()
    col.plot(freq,y.real)
    col.axvline(x=0,color = 'r')
    col.set_ylim([0,0.2])
    # plt.yscale('Log')


    mamp[count-1] = np.max(y.real)
    temp_mamp = mamp[count-1]
    temp_yreal = y.real
    temp_comp = np.where(temp_mamp == temp_yreal)
    # print(freq[what])
    temp_freqOfwhat = freq[temp_comp]
    # print(why[0])
    mfreq[count-1] = temp_freqOfwhat[0]

    
    count += 1
    if count == 7: break

# plt.yscale('log')
print(mamp)
print(mfreq)
fig.tight_layout()

plt.show()
# plt.title("FFT (D1CH1Cl1)")
# plt.ylabel("Amplitude")
# plt.xlabel("Sample")

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[0.00343322 0.12177012 0.08073051 0.05095225 0.04438057 0.05832643]
[21.16234997  7.14711138 16.85006878 18.01506715  5.56242274  9.77747808]


In [ ]:
fig, ax = plt.subplots(nrows=2, ncols=3)

# channel used array
chi = data[0][:,2]
# class array
cl = data[0][:,9]

count = 1
for row in ax:
  for col in row:
    cli = np.where(cl == count)
    chicli = chi[cli]
    y = fft(chicli)
    n = chicli.size
    timestep = 0.001
    freq = np.fft.fftfreq(n, d = timestep)
    col.plot(freq,abs(y))
    col.axvline(x=0,color = 'r')
    col.set_ylim([0,0.2])
    count += 1
    if count == 7: break

fig.tight_layout()
plt.show()

Testing

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.01, 5.0, 0.01)
s1 = np.sin(2 * np.pi * t)
s2 = np.exp(-t)
s3 = np.sin(4 * np.pi * t)

ax1 = plt.subplot(311)
plt.plot(t, s1)
plt.setp(ax1.get_xticklabels(), fontsize=6)

# share x only
ax2 = plt.subplot(312, sharey=ax1)
plt.plot(t, s2)
# make these tick labels invisible
plt.setp(ax2.get_xticklabels(), visible=False)

# share x and y
ax3 = plt.subplot(313)
plt.plot(t, s3)
plt.xlim(0.01, 5.0)
plt.show()

In [3]:
x1 = data[0][:,1]
y1 = fft(x1)
n = x1.size
timestep = 0.001
freq = np.fft.fftfreq(n, d = timestep)
plt.plot(freq,
y1.real)
plt.show()


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Shift (50) Windowed fft 

In [ ]:
x = data[0][:,1]

mov = 200
y = np.zeros((len(x),mov))
z = np.zeros((len(x)))

for i in range(len(x)-mov):
  temp = fft(x[i:(i+mov)])
  z[i] = sum(temp)/len(temp)
  for j in range(mov):
    y[i,j] = temp[j]

plt.plot(y,color = 'r')


plt.ylabel("Amplitude")
plt.xlabel("Sample")
# plt.legend()

cusignal Example: 

In [ ]:
import cusignal
import cupy as cp
from cupy.fft import fft, fftshift
import matplotlib.pyplot as plt

In [ ]:
window = cusignal.blackman(51)
plt.plot(cp.asnumpy(window))
plt.title("Blackman window")
plt.ylabel("Amplitude")
plt.xlabel("Sample")

In [ ]:
plt.figure()
A = fft(window, 2048) / (len(window)/2.0)
freq = cp.linspace(-0.5, 0.5, len(A))
response = cp.abs(fftshift(A / cp.abs(A).max()))
response = 20 * cp.log10(cp.maximum(response, 1e-10))
plt.plot(cp.asnumpy(freq), cp.asnumpy(response))
plt.axis([-0.5, 0.5, -120, 0])
plt.title("Frequency response of the Blackman window")
plt.ylabel("Normalized magnitude [dB]")
plt.xlabel("Normalized frequency [cycles per sample]")